name: Maxwell Ciotti
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments
description: "A central hub uniting my journal, portfolio, and lab"
url: "http://mdc.io"
permalink: /journal/:title/
feed: /journal/feed/
logo: /img/m-transparent.svg
trackingID: 5515d88dde2e261e74002ed7
email: me@mdc.io
role: "Student designer & web developer"
timezone: America/Chicago
encoding: utf-8
collections:
  projects:
  experiments:
    output: true
    permalink: /lab/:title/
defaults:
  - scope:
      path: ""
      type: experiments
    values:
      layout: experiment
exclude: [styles, vendor, misc, design, Gemfile, Gemfile.lock, serve.sh, readme.md, CNAME]
