name: Maxwell Ciotti
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments
description: "A central hub of Maxwell Ciotti's journal, portfolio, and lab"
url: "http://mdc.io"
permalink: /journal/:title/
github: mdciotti
twitter: mdciotti
email: max@mdc.io
role: "Student designer & web developer"
timezone: America/Chicago
encoding: utf-8
collections:
  - projects
  - experiments
exclude: [styles, vendor, misc]
keep_files: [css]
