name: Maxwell Ciotti
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments
description: "A central hub uniting Maxwell Ciotti's journal, portfolio, and lab"
url: "http://mdc.io"
permalink: /journal/:title/
logo: /img/m-transparent.svg
email: max@mdc.io
role: "Student designer & web developer"
timezone: America/Chicago
encoding: utf-8
collections:
  - projects
  - experiments
exclude: [styles, vendor, misc, design]
